resources:
  - native-deployment.yaml
  - native-service.yaml
  - native-daemonset.yaml
  - nativeDisruptionBudget.yaml

labels:
  - pairs:
      app: native-app
    includeSelectors: true

nameSuffix:
  -v1