resources:
  - ../../base
  - dev-namespace.yaml

namePrefix: dev-

namespace: dev-namespace

configurations:
  - nameref.yaml

labels:
  - pairs:
      env: dev
    includeSelectors: true
    includeTemplates: true

configMapGenerator:
  - name: app-config
    literals:
      - database_host=dev-db-service
      - database_name=dev-user-db

secretGenerator:
  - name: db-secret
    literals:
      - username=admin
      - password=password

patches:
  - path: patch-affinity.yaml