resources:
  - db-deployment.yaml
  - db-service.yaml

labels:
  - pairs:
      app: mongo-db
    includeSelectors: true

configMapGenerator:
  - name: mongo-config-map
    files:
      - mongo.properties